### PR TITLE
Create French translation

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

A small translation in French

I will work on your other apps later in January I think :)

### CODE REVIEW

**Comment by tibbi** [comment]
Nice, thanks :) Feel free translating the app names too (first string), I think they should be translated. For Simple Thank You you can just type the translation here in the comment, no need to create another pull request.

**Comment by Poussinou** [comment]
OK, the name could be something like "Un petit Merci" it sounds cute ;)

I'll remember to translate the names of the apps for the other ones.

**Comment by tibbi** [comment]
Alright cool, thanks. I wrote a guide how to set up a file watcher which will send you an email whenever a file changes, you can check it out at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-get-notified-if-a-translated-file-changes . That way you won't have to keep checking files over and over, if you plan keeping the translations up to date :)

**Comment by Poussinou** [comment]
Waaaah it looks awesome, I wasn't aware of this tool, I'll use it thanks :)

**Pull request merged**
