### PR TITLE
Dutch

### PR DESCRIPTION
**Pull request by ltGuillaume**

### CODE REVIEW

**Comment by ltGuillaume** [comment]
Can you see how many Dutch users you have for your apps? (# downloaders from The Netherlands)

**Comment by tibbi** [comment]
Well it is more difficult to see as Google removed the total lifetime install numbers from the PC dashboard. I can list the calendar lifetime downloads from my mobile app dev console. But since Netherlands arent at the top 10 popular countries for the gallery, I can list just the amount of active users of it (users who launched the app at least once in the last month)
Calendar - 48 617, 2.5%
Calendar Pro - 2408, 3.1%
Gallery - 18 748
Gallery Pro - 4964

**Comment by ltGuillaume** [comment]
More than I expected, quite a lot! And this doesn't include F-Droid installs.

**Comment by tibbi** [comment]
yeah, f-droid has just a couple users though, so it wouldnt make a big difference anyway :)

**Comment by tibbi** [comment]
actually Notes seem to be quite popular there, for the free one Netherlands is the third most popular country
Notes - 41 220 lifetime downloads, 10,8%, but the paid one isnt at the top 10 countries anymore

**Comment by ltGuillaume** [comment]
I found that many notes apps aren't properly translated (either crappy machine translations or not translated at all), so that may have contributed it. Not to pat myself on the back, haha, but 1) in general, looking for such apps for parents etc., proper translations are a key factor and 2) specifically, I found other notes apps do a particularly bad job at translations somehow.

**Comment by tibbi** [comment]
sure, translations definitely help. There are always some country specific variables that affect such things too

**Pull request merged**
