### PR TITLE
Fix/language color

### PR DESCRIPTION
**Pull request by FunkyMuse**

### CODE REVIEW

**Comment by tibbi** [comment]
they shouldnt use the same color. The value should be less visible, like it works in other themes

**Comment by FunkyMuse** [comment]
let me know if this is an okay alpha

**Comment by tibbi** [comment]
changed it to 0.6, should be good now. Thanks

**Comment by FunkyMuse** [comment]
> changed it to 0.6, should be good now. Thanks

I'll change in commons to reflect it everywhere

**Pull request merged**
